# fly.toml app configuration file generated for xp-bot on 2025-04-12T20:09:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'xp-bot'
kill_signal = "SIGINT"
kill_timeout = 5
processes = { worker = "python bot.py" }

[env]
PORT = "8080"
ENV = "prod"

[[services]]
internal_port = 8080
protocol = "tcp"
processes = ["worker"]  # <--- This line matches the process defined above

  [[services.ports]]
  port = 8080
  handlers = []  # No HTTP handler

[checks]  # Optional - disables health checks