# fly.toml app configuration file for xp-bot Discord bot
# See https://fly.io/docs/reference/configuration/

app = 'xp-bot'
primary_region = 'iad'  # Change to your preferred region

kill_signal = "SIGINT"
kill_timeout = 10

[build]
  dockerfile = "Dockerfile.prod"

[env]
ENV = "prod"

[processes]
worker = "python bot.py"

# Discord bots don't need exposed ports, so no [[services]] section

# VM resources - adjust based on needs
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256