# fly.toml app configuration file for xp-bot Discord bot
# See https://fly.io/docs/reference/configuration/

app = 'xp-bot-young-brook-5946'
primary_region = 'ord'

kill_signal = "SIGINT"
kill_timeout = 10

[build]
  dockerfile = "Dockerfile.prod"

[env]
  ENV = "prod"

# Discord bots don't need HTTP service - remove auto-stop behavior
# Keep the bot running 24/7

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
